set_property SRC_FILE_INFO {cfile:/home/agata/FpgaFlashTester/flash_programmer/flash_programmer.srcs/constrs_1/imports/new/constaint.xdc rfile:../../../flash_programmer.srcs/constrs_1/imports/new/constaint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports led_light]
set_property src_info {type:XDC file:1 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 12 [get_ports led_light]
set_property src_info {type:XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports led_light]
set_property src_info {type:XDC file:1 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports led_light]
set_property src_info {type:XDC file:1 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports CLK25MHZ]
set_property src_info {type:XDC file:1 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports CLK25MHZ]
